concurrent = 20
check_interval = 15

[session_server]
  session_timeout = 1800

[[runners]]
  name = "[lab-docker-01]docker-runner"
  url = "http://gitlab.mikemomo.com/"
  token = "GR1348941LPuajLWb2crf4Zn7zSwr"
  executor = "docker"
  builds_dir = "/builds"
  cache_dir = "/tmp"
  [runners.custom_build_dir]
    enabled = true
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "centos:8"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/data-disk/gitlab-runner/image/tmp:/tmp", "/data-disk/gitlab-runner/image/builds:/builds"]
    shm_size = 5000000