concurrent = 20
check_interval = 15

[session_server]
  session_timeout = 1800

[[runners]]
  name = "lab-docker-01"
  url = "http://gitlab.mikemomo.com"
  token = "xStyvT86cJT-TTZixDky"
  executor = "docker"
  builds_dir = "/builds"
  cache_dir = "/tmp"
  [runners.custom_build_dir]
    enabled = true
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "centos:8"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/data-disk/gitlab-runner/image-dev/cache:/cache", "/data-disk/gitlab-runner/image-dev/builds:/builds"]
    shm_size = 0
